:: Static Banner
set line01=echo -------------------------------------------------------------------------------
set line02=echo   ANDROID VERSION: %device_sw_name% %ro_build_version_release%    SU VERSION: %suversion%
set line03=echo -------------------------------------------------------------------------------
set line04=echo -     **    *****   *****                                                     -
set line05=echo -    ****   **  **  **  **                                                    -
set line06=echo -   **  **  **  **  **  **                                                    -
set line07=echo -   **  **  **  **  *****                adbtoolkit.com                       -
set line08=echo -   ******  **  **  **  **                                                    -
set line09=echo -   **  **  **  **  **  **                                                    -
set line10=echo -   **  **  *****   *****                                                     -
set line11=echo -                                                     **                      -
set line12=echo -           ******                  ****    **        **     **               -
set line13=echo -             **                      **    **  **           **               -
set line14=echo -             **     ****    ****     **    **  **  ****    ******            -
set line15=echo -             **    **  **  **  **    **    ** **     **     **               -
set line16=echo -             **    **  **  **  **    **    ** **     **     **               -
set line17=echo -             **     ****    ****   ******  **  **  ******    ****            -
set line18=echo -                                                                             -
set line19=echo -   esc0rtd3w@gmail.com             Windows XP/Vista/7               v%releasever%   -
set line20=echo -------------------------------------------------------------------------------
set line21=echo   DEVICE: %ro_product_manufacturer_text% %ro_product_model% (%ro_product_board%) / %ro_product_cpu_abi_text%    SERIAL#: %autoserial% 
set line22=echo -------------------------------------------------------------------------------