:: Static Banner
set line01=echo -------------------------------------------------------------------------------
set line02=echo -     **    *****   *****                                                     -
set line03=echo -    ****   **  **  **  **                                                    -
set line04=echo -   **  **  **  **  **  **                                                    -
set line05=echo -   **  **  **  **  *****                adbtoolkit.com                       -
set line06=echo -   ******  **  **  **  **                                                    -
set line07=echo -   **  **  **  **  **  **                                                    -
set line08=echo -   **  **  *****   *****                                                     -
set line09=echo -                                                                             -
set line10=echo -           ******                  ****    **        **     **               -
set line11=echo -             **                      **    **  **           **               -
set line12=echo -             **     ****    ****     **    **  **  ****    ******            -
set line13=echo -             **    **  **  **  **    **    ** **     **     **               -
set line14=echo -             **    **  **  **  **    **    ****      **     **               -
set line15=echo -             **    **  **  **  **    **    ** **     **     **               -
set line16=echo -             **     ****    ****   ******  **  **  ******    ****            -
set line17=echo -                                                                             -
set line18=echo -   esc0rtd3w@gmail.com        {###########}~   Happy 4:20           v%releasever%   -
set line19=echo -------------------------------------------------------------------------------
set line20=echo   SU:%suversion%  DEVICE:%ro_product_name%  BOARD:%ro_product_board%  SERIAL#:%autoserial%
set line21=echo -------------------------------------------------------------------------------