:: Static Banner
set line01=echo ------------------------------------------------------------------------------
set line02=echo  -
set line03=echo  -
set line04=echo  -
set line05=echo  -
set line06=echo  -
set line07=echo  -
set line08=echo  -
set line09=echo  -
set line10=echo  -
set line11=echo  User: %ro_build_user%     Region: %ro_product_locale_region%     Language: %ro_product_locale_language%
set line12=echo  -
set line13=echo  Manufacturer: %ro_product_manufacturer_text%     Device: %ro_product_name%     Board:%ro_product_board%
set line14=echo  -
set line15=echo  CPU1: %ro_product_cpu_abi%     CPU2: %ro_product_cpu_abi%
set line16=echo  -
set line17=echo  Android Version: %device_sw_name% %ro_build_version_release%
set line18=echo  -
set line19=echo  -
set line20=echo  -
set line21=echo ------------------------------------------------------------------------------