@echo off

title Android ADB Toolkit v%releasever%                              -[ adbtoolkit.com ]-

color 0e


:: Setting zflag to 0 above reset so it is known if a reboot has been issued
set zflag=0


:reset

:set_var
set action=99
set apkfile=NONE
set apkuninstall=%adb% shell rm
::set apkuninstallsystem=%adb% shell rm /system/app/
::set apkuninstalluser=%adb% shell rm /data/app/
::set apkuninstall=%adb% uninstall
::set apkuninstall=%adb% shell pm uninstall
set filemode=UNINSTALL [Method: %adb% shell rm]

::call "scripts\get_info_bar.cmd"




:: Close any other open package lists
nircmd win close ititle "adbtk-list-packages.tmp"


:: Removing Temp Text File for Packages
del /f /q "%temp%\adbtk-list-packages.tmp"


::Check for zflag status
if %zflag%==1 goto main


:: Checking for packages on device and creating temp text file to display them all

%showbanner%
echo.
echo.
echo Building Package List From Device....
echo.
%adbstop%

%showbanner%
echo.
echo.
echo Building Package List From Device....
echo.
%adbstart%

%showbanner%
echo.
echo.
echo Building Package List From Device....
echo.

echo -------------------------------------- > "%temp%\adbtk-list-packages.tmp"
echo      Installed Packages On Device >> "%temp%\adbtk-list-packages.tmp"
echo. >> "%temp%\adbtk-list-packages.tmp"
echo Automatically Generated By ADB Toolkit >> "%temp%\adbtk-list-packages.tmp"
echo -------------------------------------- >> "%temp%\adbtk-list-packages.tmp"
echo. >> "%temp%\adbtk-list-packages.tmp"

%adb% shell pm list packages -f >> "%temp%\adbtk-list-packages.tmp"
start notepad.exe "%temp%\adbtk-list-packages.tmp"


:: Permissions
::%adb% shell chmod 644 /system/app/*



:main
set zflag=0
%showbanner%
echo.
echo.
echo Current File Mode: %filemode%
echo.
echo.
echo.
echo.
echo Type the path and APK file on your device and press ENTER....
echo.
echo You can also copy and paste from the application list that should be open.
echo.
echo.
echo --------
echo Examples
echo --------
echo.
echo User App: /data/app/Facebook.apk
echo.
echo System App: /system/app/Calculator.apk
echo.
echo.
%cocolor% 0b
echo R) Return To Previous Menu
%cocolor% 0e
echo.

set /p apkfile=

:: Linux Style Prompt
::set /p apkfile=root@root/# 

:: Debug Only (next 2 lines)
::echo %apkfile%
::pause>nul

:: Check QUIT first so it will exit properly and be able to reject higher numbers
if %apkfile%==R goto end
if %apkfile%==r goto end


:: Check Z flag for reboot after uninstall
if %apkfile%==Z goto zflag
if %apkfile%==z goto zflag


if %apkfile%==NONE goto main
if not %apkfile%==NONE goto uninstall
goto end


:zflag
%adb% reboot
set zflag=1
goto reset


:uninstall
%showbanner%
echo.
echo.
echo Currently Uninstalling: %apkfile%
echo.
echo.

%apkuninstall% %apkfile%



pause

goto reset


:end


:: Close any other open package lists
nircmd win close ititle "adbtk-list-packages.tmp"


